export const songs = [
  {
    title: 'Genda fool',
    artist: 'Badshah',
    url: 'https://res.cloudinary.com/domavvtdl/video/upload/v1640949566/song/Genda_Phool_-_Badshah_ztcp7h.mp3',
    id: 1,
    duration: '2:22',
  },
  {
    title: 'ek uncha lmba',
    artist: 'asees kaur',
    url: 'https://res.cloudinary.com/domavvtdl/video/upload/v1640945622/song/uncha-lamba-kad-asees-kaur-128-kbps-sound_xys4bx.mp3',
    id: 2,
    duration: '3:10',
  },
  {
    title: 'mahebooba',
    artist: 'rocky',
    url: require('../assets/songs/Mehbooba.mp3'),
    id: 3,
    duration: '2:10',
  },
  {
    title: 'srivali',
    artist: 'allu arjun',
    url: require('../assets/songs/Srivalli.mp3'),
    id: 4,
    duration: '3:10',
  },
  {
    title: 'Ami tomar',
    artist: 'Arjit singh',
    url: require('../assets/songs/Ami.mp3'),
    id: 5,
    duration: '3:10',
  },
  {
    title: 'har har mahadev',
    artist: 'ramesh',
    url: require('../assets/songs/Mahadeva.mp3'),
    id: 6,
    duration: '3:10',
  },
  {
    title: 'mahebooba',
    artist: 'rocky',
    url: require('../assets/songs/Mehbooba.mp3'),
    id: 7,
    duration: '3:55',
  },
  {
    title: 'srivali',
    artist: 'allu arjun',
    url: require('../assets/songs/Srivalli.mp3'),
    id: 8,
    duration: '3:10',
  },
];
